<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EasyShopper.Domain\EasyShopper.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Interfaces\" />
    <Folder Include="Models\Orders\Commands\" />
    <Folder Include="Models\Orders\DTOs\" />
    <Folder Include="Models\Products\DTOs\" />
    <Folder Include="Models\Products\Queries\" />
    <Folder Include="Models\Users\Commands\" />
    <Folder Include="Models\Users\DTOs\" />
    <Folder Include="Models\Users\Queries\" />
  </ItemGroup>

</Project>
